In [12]:
import pandas as pd
import numpy as np
import glob

In [7]:
first = pd.read_csv('final/movies_2010.csv')

In [16]:
files = glob.glob('final/*.csv')

df_all = first.copy()

for file in files:
    if 'movies_2010' not in file:
        file_df = pd.read_csv(file)
        df_all= pd.concat([df_all, file_df], axis = 0, sort=False)

In [17]:
df_all

,Title,Director,Year,Plot,Genre,Unnamed: 0
0,666,"Honey Blanca, Celso Ad. Castillo",2010,NaN,Horror,NaN
1,Ang Tanging Ina Mo (Last na 'To!),Wenn V. Deramas,2010,A dedicated mother is told that she only has a...,"Comedy, Drama",NaN
2,Antipo,Joseph Laban,2010,NaN,"Short, Drama",NaN
3,"Babe, I Love You",Mae Cruz,2010,A straight laced university professor haunted ...,"Drama, Romance",NaN
4,Cinco,Frasco MortizEnrico SantosCathy Garcia-MolinaA...,2010,"Five sex-themed stories: Story 1: At night, wh...",Romance,NaN
...,...,...,...,...,...,...
30,"Wedding Tayo, Wedding Hindi",Jose Javier Reyes,2011,Two women are at very different stages of thei...,Comedy,30.0
31,Who's That Girl,Wenn V. Deramas,2011,Elizabeth Pedroza (Curtis) has been crushing t...,Comedy,31.0
32,Won't Last A Day Without You,Raz Dela Torre,2011,A female radio DJ who has a popular relationsh...,"Comedy, Romance",32.0
33,"Yesterday, Today, Tomorrow",Jun Lana,2011,This is a story of people and the secrets that...,"Drama, Romance",33.0
34,Zombadings 1: Patayin sa Shokot si Remington,Jade Castro,2011,Remington is in love with Hannah but she finds...,"Comedy, Horror, Romance",34.0

In [29]:
#just to check
years = np.arange(2010,2021)

In [32]:
for year in years:
    print(year)
    print(df_all[df_all['Year']==year].count())
    print()

2010
Title         27
Director      27
Year          27
Plot          21
Genre         25
Unnamed: 0     0
dtype: int64

2011
Title         70
Director      70
Year          70
Plot          66
Genre         70
Unnamed: 0    70
dtype: int64

2012
Title         54
Director      54
Year          54
Plot          38
Genre         49
Unnamed: 0    54
dtype: int64

2013
Title         0
Director      0
Year          0
Plot          0
Genre         0
Unnamed: 0    0
dtype: int64

2014
Title         101
Director      101
Year          101
Plot           80
Genre          88
Unnamed: 0    101
dtype: int64

2015
Title         90
Director      90
Year          90
Plot          78
Genre         84
Unnamed: 0    90
dtype: int64

2016
Title         109
Director      109
Year          109
Plot           94
Genre          99
Unnamed: 0    109
dtype: int64

2017
Title         114
Director      114
Year          114
Plot           86
Genre         100
Unnamed: 0    114
dtype: int64

2018
Title         124
Director      124
Year          124
Plot          106
Genre         115
Unnamed: 0    124
dtype: int64

2019
Title         123
Director      123
Year          123
Plot          105
Genre         118
Unnamed: 0    123
dtype: int64

2020
Title         42
Director      42
Year          42
Plot          35
Genre         39
Unnamed: 0    42
dtype: int64

In [ ]:
df_all.to_csv('movies_all.csv', index=False)