In [1]:
!pip install git+https://github.com/alberanid/imdbpy

Collecting git+https://github.com/alberanid/imdbpy
  Cloning https://github.com/alberanid/imdbpy to c:\users\eric\appdata\local\temp\pip-req-build-6kshoc9l
Requirement already satisfied: SQLAlchemy in c:\users\eric\scoop\apps\miniconda3\4.9.2\lib\site-packages (from IMDbPY==2021.2.24) (1.3.23)
Requirement already satisfied: lxml in c:\users\eric\scoop\apps\miniconda3\4.9.2\lib\site-packages (from IMDbPY==2021.2.24) (4.6.2)

In [2]:
!pip install tqdm

Requirement already satisfied: tqdm in c:\users\eric\scoop\apps\miniconda3\4.9.2\lib\site-packages (4.55.1)

In [3]:
import pandas as pd
import numpy as np
import imdb

In [4]:
df_movies = pd.read_csv('movies_2013.csv')

In [5]:
df_movies

,Title,Director,Year
0,Menor de Edad,Joel Lamangan,2013
1,Seduction,Peque Gallaga,2013
2,"I Love You, Pare Ko1",Neal Tan,2013
3,Gabriel (Ito ang Kuwento Ko)1,Ronald M. Rafer,2013
4,A Moment in Time,Emmanuel Quindo Palo,2013
...,...,...,...
99,Pagpag: Siyam na Buhay,Frasco S. Mortiz,2013
100,"10,000 Hours",Joyce Bernal,2013
101,Pedro Calungsod: Batang Martir,Francis O. Villacorta (Producer-Writer-Directo...,2013
102,"Boy Golden: Shoot to Kill, the Arturo Porcuna ...",Chito S. Roño,2013
103,Kaleidoscope World,Liza Cornejo,2013

In [6]:
import imdb
from tqdm import tqdm

ia = imdb.IMDb()

bar = tqdm(df_movies.iterrows())

for index, row in bar:
    movies = ia.search_movie(row['Title'])
    if movies:
        correct_movie = None
        for movie in movies:
            bar.set_description(row['Title'])
            m = ia.get_movie(movie.getID())
            if m.get('year') == row['Year']:
                correct_movie = m
            if correct_movie:
                break
        if correct_movie:
            plot = m.get('plot')
            if plot:
                df_movies.loc[index, 'Plot'] = plot[0]
            genre = m.get('genre')    
            if genre:
                df_movies.loc[index, 'Genre'] = ', '.join(genre)

Kaleidoscope World: : 104it [20:02, 11.57s/it]

In [7]:
df_movies

,Title,Director,Year,Plot,Genre
0,Menor de Edad,Joel Lamangan,2013,Fifteen-year-old Jen doesn't have a very happy...,Drama
1,Seduction,Peque Gallaga,2013,A fireman is in love to his landlady but is se...,Drama
2,"I Love You, Pare Ko1",Neal Tan,2013,NaN,NaN
3,Gabriel (Ito ang Kuwento Ko)1,Ronald M. Rafer,2013,NaN,Drama
4,A Moment in Time,Emmanuel Quindo Palo,2013,A struggling artist travels to Amsterdam to tr...,"Drama, Romance"
...,...,...,...,...,...
99,Pagpag: Siyam na Buhay,Frasco S. Mortiz,2013,The spirit of a recently deceased man hunts do...,Horror
100,"10,000 Hours",Joyce Bernal,2013,A senator is forced to go on the run after kil...,"Action, Drama, Thriller"
101,Pedro Calungsod: Batang Martir,Francis O. Villacorta (Producer-Writer-Directo...,2013,"Pedro Calungsod, a young Filipino man, leaves ...","Biography, Crime, Drama, History, Thriller, War"
102,"Boy Golden: Shoot to Kill, the Arturo Porcuna ...",Chito S. Roño,2013,Boy Golden is a 2013 Filipino film loosely bas...,Drama
103,Kaleidoscope World,Liza Cornejo,2013,A hip hop dance film featuring Filipino world ...,"Drama, Family, Musical, Romance"

In [8]:
# update csv with plot 
df_movies.to_csv('movies_2013.csv', index=False)